### ISSUE TITLE
I cant see the logs on Chrome Dev Tools with React Native

### ISSUE THREAD

**Issue by matthewfang** [winterbe/mobx-logger#10] opened 2017-03-14 12:33 UTC
![image](https://cloud.githubusercontent.com/assets/20057066/23900772/611f06ec-08f5-11e7-9938-bf260da49de1.png)

predicate get true, but i also cant see the logs on chrome , how can i get it works?

**Comment by yordis** [comment] 2017-10-29 17:28
@winterbe Hey man, I recently start using MobX and I don't see any logs as well. Any ideas what could be?

**Comment by Kennytian** [comment] 2017-11-08 04:11
@matthewfang  @yordis  Hello, all!  I use [React Native Debugger](https://github.com/jhen0409/react-native-debugger) can see logs

**Comment by winterbe** [comment] 2018-03-26 12:02
I close this issue as I cannot reproduce the issue.

**Closed as completed by winterbe** 2018-03-26 12:02 UTC
